### ISSUE TITLE
Explore regularization techniques

### ISSUE THREAD

**Issue by mathiashusted** [gromdimon/brain-segment#26]
Check docs/optimizations.md

**Comment by gromdimon** [comment]
Our docs: https://github.com/gromdimon/brain-segment/blob/main/docs/optimizations.md#regularization-techniques

The workflow:
- Run all different possibilities of the upgrades:
1) We can test dropout=0 and small dropout=0.2 (further values are not really needed, since we certainly won't have overfitting)
2) Explore all norms: https://github.com/Project-MONAI/MONAI/blob/96bfda00c6bd290297f5e3514ea227c6be4d08b4/monai/networks/nets/unet.py#L120
- Compare results on W&B

**Comment by mathiashusted** [comment]
Thanks @evin222 for the data. We can say now that it's most likely better to reduce the dropout from 0.1 to 0 (our dataset is large enough so that it doesn't require dropout layers)
